# based on: https://packaging.python.org/guides/supporting-windows-using-appveyor/

environment:
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64

install:
  - |
    %PYTHON%\python.exe -m pip install --upgrade -q pip wheel setuptools
    %PYTHON%\python.exe -m pip list --format columns

# only used when compiling (for Python with C extensions this is done in the after_test)
build: off

test_script:
  - echo Skipped for now

after_test:
  - |
    %PYTHON%\python.exe setup.py bdist_wheel

artifacts:
  - path: dist\*
